import { BrancheInfo } from "@/helpers/types";

export const branches: BrancheInfo[] = [
  {
    // name: "Acto Academia Várzea",
    name: "Várzea",
    address: "Av. Afonso Olindense, nº 1090",
    neighborhood: "Varzea",
    city: "Recife",
    state: "PE",
    zipCode: "50810-000",
    slug: "varzea",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/acto-dev.appspot.com/o/branches%2Fbranche_varzea.jpg?alt=media&token=0da6a261-dd21-46ac-a176-b3e3aeb2cb4d",
    plans: [
      {
        name: "INFINITY START – FIDELIDADE",
        link: "https://evo-totem.w12app.com.br/actoacademia/1/site/qFGpuVG2CYkGZVajHu57Ow%5BEQUAL%5D%5BEQUAL%5D",
        value: 99.9,
        benefits: [
          "FIDELIDADE DE 12 MESES",
          "MUSCULAÇÃO E AULAS COLETIVAS",
          "NÃO COMPROMETE O LIMITE",
          "METODOLOGIA EXCLUSIVA",
          "MAPEAMENTO DE SINTOMAS",
          "TREINOS EXCLUSIVOS A CADA 30 DIAS",
          "APLICATIVO EXCLUSIVO",
        ],
      },
      {
        name: "INFINITY START",
        link: "https://evo-totem.w12app.com.br/actoacademia/1/site/i681zQSE0wGa4tBjj0CKyQ%5BEQUAL%5D%5BEQUAL%5D",
        value: 109.9,
        benefits: [
          "ZERO MULTA",
          "ZERO FIDELIDADE",
          "HORÁRIO LIVRE",
          "ACESSO ILIMITADO",
          "NÃO COMPROMETE O LIMITE",
          "METODOLOGIA EXCLUSIVA",
          "MAPEAMENTO DE SINTOMAS",
          "MUSCULAÇÃO E AULAS COLETIVAS",
          "TREINOS EXCLUSIVOS A CADA 30 DIAS",
          "APLICATIVO EXCLUSIVO",
        ],
      },
      {
        name: "INFINITY MAX",
        link: "https://evo-totem.w12app.com.br/actoacademia/1/site/iVffUM%5BBAR%5D%5BPLUS%5DMSz2HHuRlGqfiw%5BEQUAL%5D%5BEQUAL%5D",
        value: 129.9,
        benefits: [
          "+ VANTAGENS",
          "ACESSO LIVRE A TODA REDE",
          "LEVE 5 AMIGOS NO MÊS",
          "ZERO MULTA",
          "ZERO FIDELIDADE",
          "HORÁRIO LIVRE",
          "ACESSO ILIMITADO",
          "ACESSO EM TODA REDE",
          "NÃO COMPROMETE O LIMITE",
          "METODOLOGIA EXCLUSIVA",
          "MAPEAMENTO DE SINTOMAS",
          "MUSCULAÇÃO E AULAS COLETIVAS",
          "TREINOS EXCLUSIVOS A CADA 30 DIAS",
          "APLICATIVO EXCLUSIVO",
        ],
      },
    ],
  },
  {
    name: "Massangana",
    address: "Av. Zequinha Barreto, nº 150",
    neighborhood: "Massangana",
    city: "Jaboatão dos Guararapes",
    state: "PE",
    zipCode: "54400-090",
    slug: "massangana",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/acto-dev.appspot.com/o/branches%2Fbranche_massangana.jpg?alt=media&token=5c0df52e-07d5-4f6d-9bdf-920a35f1c093",
    plans: [
      {
        name: "INFINITY START – FIDELIDADE",
        link: "https://evo-totem.w12app.com.br/actoacademia/2/site/W4xbhycdyDd%5BBAR%5DxV8tdYABmQ%5BEQUAL%5D%5BEQUAL%5D",
        value: 99.9,
        benefits: [
          "FIDELIDADE DE 12 MESES",
          "MUSCULAÇÃO E AULAS COLETIVAS",
          "NÃO COMPROMETE O LIMITE",
          "METODOLOGIA EXCLUSIVA",
          "MAPEAMENTO DE SINTOMAS",
          "TREINOS EXCLUSIVOS A CADA 30 DIAS",
          "APLICATIVO EXCLUSIVO",
        ],
      },
      {
        name: "INFINITY START",
        link: "https://evo-totem.w12app.com.br/actoacademia/2/site/e5OuNNWVeqISSbt%5BBAR%5Dd9JpHw%5BEQUAL%5D%5BEQUAL%5D",
        value: 109.9,
        benefits: [
          "ZERO MULTA",
          "ZERO FIDELIDADE",
          "HORÁRIO LIVRE",
          "ACESSO ILIMITADO",
          "NÃO COMPROMETE O LIMITE",
          "METODOLOGIA EXCLUSIVA",
          "MAPEAMENTO DE SINTOMAS",
          "MUSCULAÇÃO E AULAS COLETIVAS",
          "TREINOS EXCLUSIVOS A CADA 30 DIAS",
          "APLICATIVO EXCLUSIVO",
        ],
      },
      {
        name: "INFINITY MAX",
        link: "https://evo-totem.w12app.com.br/actoacademia/2/site/8VGMoOnBLSKafcLuXHBygA%5BEQUAL%5D%5BEQUAL%5D",
        value: 129.9,
        benefits: [
          "+ VANTAGENS",
          "ACESSO LIVRE A TODA REDE",
          "LEVE 5 AMIGOS NO MÊS",
          "ZERO MULTA",
          "ZERO FIDELIDADE",
          "HORÁRIO LIVRE",
          "ACESSO ILIMITADO",
          "ACESSO EM TODA REDE",
          "NÃO COMPROMETE O LIMITE",
          "METODOLOGIA EXCLUSIVA",
          "MAPEAMENTO DE SINTOMAS",
          "MUSCULAÇÃO E AULAS COLETIVAS",
          "TREINOS EXCLUSIVOS A CADA 30 DIAS",
          "APLICATIVO EXCLUSIVO",
        ],
      },
    ],
  },
  {
    name: "Cordeiro",
    address: "R. Cláudio Brotherhood, nº 96",
    neighborhood: "Cordeiro",
    city: "Recife",
    state: "PE",
    zipCode: "50721-260",
    slug: "cordeiro",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/acto-dev.appspot.com/o/branches%2Fbranche_cordeiro.jpg?alt=media&token=0b1ffee0-3491-4017-a31b-7e0a64b56e9a",
    plans: [
      {
        name: "INFINITY START – FIDELIDADE",
        link: "https://evo-totem.w12app.com.br/actoacademia/5/site/ixNnMrON8x6zInt2N0%5BPLUS%5Dwiw%5BEQUAL%5D%5BEQUAL%5D",
        value: 99.9,
        benefits: [
          "FIDELIDADE DE 12 MESES",
          "MUSCULAÇÃO E AULAS COLETIVAS",
          "NÃO COMPROMETE O LIMITE",
          "METODOLOGIA EXCLUSIVA",
          "MAPEAMENTO DE SINTOMAS",
          "TREINOS EXCLUSIVOS A CADA 30 DIAS",
          "APLICATIVO EXCLUSIVO",
        ],
      },
      {
        name: "INFINITY START",
        link: "https://evo-totem.w12app.com.br/actoacademia/5/site/i5TLOeLbcO54JkLb2dbcLw%5BEQUAL%5D%5BEQUAL%5D",
        value: 109.9,
        benefits: [
          "ZERO MULTA",
          "ZERO FIDELIDADE",
          "HORÁRIO LIVRE",
          "ACESSO ILIMITADO",
          "NÃO COMPROMETE O LIMITE",
          "METODOLOGIA EXCLUSIVA",
          "MAPEAMENTO DE SINTOMAS",
          "MUSCULAÇÃO E AULAS COLETIVAS",
          "TREINOS EXCLUSIVOS A CADA 30 DIAS",
          "APLICATIVO EXCLUSIVO",
        ],
      },
      {
        name: "INFINITY MAX",
        link: "https://evo-totem.w12app.com.br/actoacademia/5/site/Ap%5BBAR%5DoMhYLgc9OFj7aaNAjgw%5BEQUAL%5D%5BEQUAL%5D",
        value: 129.9,
        benefits: [
          "+ VANTAGENS",
          "ACESSO LIVRE A TODA REDE",
          "LEVE 5 AMIGOS NO MÊS",
          "ZERO MULTA",
          "ZERO FIDELIDADE",
          "HORÁRIO LIVRE",
          "ACESSO ILIMITADO",
          "ACESSO EM TODA REDE",
          "NÃO COMPROMETE O LIMITE",
          "METODOLOGIA EXCLUSIVA",
          "MAPEAMENTO DE SINTOMAS",
          "MUSCULAÇÃO E AULAS COLETIVAS",
          "TREINOS EXCLUSIVOS A CADA 30 DIAS",
          "APLICATIVO EXCLUSIVO",
        ],
      },
    ],
  },
  {
    name: "Iputinga",
    address: "R. São Mateus, nº 653",
    neighborhood: "Iputinga",
    city: "Recife",
    state: "PE",
    zipCode: "50680-000",
    slug: "iputinga",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/acto-dev.appspot.com/o/branches%2Fbranche_iputinga.jpg?alt=media&token=2390fdbc-cd32-4db3-acc5-278a9c8a3133",
    plans: [
      {
        name: "INFINITY START – FIDELIDADE",
        link: "https://evo-totem.w12app.com.br/actoacademia/3/site/qay%5BPLUS%5D%5BBAR%5DQQGYuqK0fqpvx50Ug%5BEQUAL%5D%5BEQUAL%5D",
        value: 99.9,
        benefits: [
          "FIDELIDADE DE 12 MESES",
          "MUSCULAÇÃO E AULAS COLETIVAS",
          "NÃO COMPROMETE O LIMITE",
          "METODOLOGIA EXCLUSIVA",
          "MAPEAMENTO DE SINTOMAS",
          "TREINOS EXCLUSIVOS A CADA 30 DIAS",
          "APLICATIVO EXCLUSIVO",
        ],
      },
      {
        name: "INFINITY START",
        link: "https://evo-totem.w12app.com.br/actoacademia/3/site/1MLti1L3K82KO%5BPLUS%5D6KmFIKEA%5BEQUAL%5D%5BEQUAL%5D",
        value: 109.9,
        benefits: [
          "ZERO MULTA",
          "ZERO FIDELIDADE",
          "HORÁRIO LIVRE",
          "ACESSO ILIMITADO",
          "NÃO COMPROMETE O LIMITE",
          "METODOLOGIA EXCLUSIVA",
          "MAPEAMENTO DE SINTOMAS",
          "MUSCULAÇÃO E AULAS COLETIVAS",
          "TREINOS EXCLUSIVOS A CADA 30 DIAS",
          "APLICATIVO EXCLUSIVO",
        ],
      },
      {
        name: "INFINITY MAX",
        link: "https://evo-totem.w12app.com.br/actoacademia/3/site/0ZADiQaSEq2047LTydZa5g%5BEQUAL%5D%5BEQUAL%5D",
        value: 129.9,
        benefits: [
          "+ VANTAGENS",
          "ACESSO LIVRE A TODA REDE",
          "LEVE 5 AMIGOS NO MÊS",
          "ZERO MULTA",
          "ZERO FIDELIDADE",
          "HORÁRIO LIVRE",
          "ACESSO ILIMITADO",
          "ACESSO EM TODA REDE",
          "NÃO COMPROMETE O LIMITE",
          "METODOLOGIA EXCLUSIVA",
          "MAPEAMENTO DE SINTOMAS",
          "MUSCULAÇÃO E AULAS COLETIVAS",
          "TREINOS EXCLUSIVOS A CADA 30 DIAS",
          "APLICATIVO EXCLUSIVO",
        ],
      },
    ],
  },
  {
    name: "Engenho do Meio",
    address: "R. Manoel Estevão da Costa, nº 119",
    neighborhood: "Iputinga",
    city: "Recife",
    state: "PE",
    zipCode: "50670-590",
    slug: "engenho",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/acto-dev.appspot.com/o/branches%2Fbranche_engenho.jpg?alt=media&token=a1167580-8e95-4130-85de-22380cd53cfb",
    plans: [
      {
        name: "INFINITY START – FIDELIDADE",
        link: "https://evo-totem.w12app.com.br/actoacademia/4/site/qCFaY5fieAgqlB%5BPLUS%5D7k5mcAw%5BEQUAL%5D%5BEQUAL%5D",
        value: 49.9,
        benefits: [
          "FIDELIDADE DE 12 MESES",
          "HORÁRIO LIVRE",
          "NÃO COMPROMETE O LIMITE",
          "METODOLOGIA EXCLUSIVA",
          "ACTO POWER",
          "ACTO VIBES",
          "ACTO MOOVE",
          "ACTO ENERGY",
          "APLICATIVO EXCLUSIVO",
        ],
      },
      {
        name: "INFINITY START",
        link: "https://evo-totem.w12app.com.br/actoacademia/4/site/Z%5BBAR%5DDZKx7AkmtZuIMYEW5Brg%5BEQUAL%5D%5BEQUAL%5D",
        value: 109.9,
        benefits: [
          "ZERO MULTA",
          "ZERO FIDELIDADE",
          "HORÁRIO LIVRE",
          "ACESSO ILIMITADO",
          "NÃO COMPROMETE O LIMITE",
          "METODOLOGIA EXCLUSIVA",
          "MAPEAMENTO DE SINTOMAS",
          "MUSCULAÇÃO E AULAS COLETIVAS",
          "TREINOS EXCLUSIVOS A CADA 30 DIAS",
          "APLICATIVO EXCLUSIVO",
        ],
      },
      {
        name: "INFINITY MAX",
        link: "https://evo-totem.w12app.com.br/actoacademia/4/site/eY5h%5BPLUS%5Dcui0pZCprI96rdTYA%5BEQUAL%5D%5BEQUAL%5D",
        value: 129.9,
        benefits: [
          "+ VANTAGENS",
          "ACESSO LIVRE A TODA REDE",
          "LEVE 5 AMIGOS NO MÊS",
          "ZERO MULTA",
          "ZERO FIDELIDADE",
          "HORÁRIO LIVRE",
          "ACESSO ILIMITADO",
          "ACESSO EM TODA REDE",
          "NÃO COMPROMETE O LIMITE",
          "METODOLOGIA EXCLUSIVA",
          "MAPEAMENTO DE SINTOMAS",
          "MUSCULAÇÃO E AULAS COLETIVAS",
          "TREINOS EXCLUSIVOS A CADA 30 DIAS",
          "APLICATIVO EXCLUSIVO",
        ],
      },
    ],
  },
];
